apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: app2
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: myappado22.azurecr.io/python-sample:v2
        ports:
        - containerPort: 80
