trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group aks-resource-group --name myakscluster
      kubectl create namespace app2 --dry-run=client -o yaml | kubectl apply -f -
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
