trigger:
  branches:
    include:
      - none

variables:
  imageName: 'python-sample'
  tag: 'v3'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'conn2'  # Replace with your ACR service connection
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(tag)
