apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-green
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-green
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-green
    spec:
      containers:
        - name: python-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
