# azure-pipelines-deploy.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --name myakscluster --resource-group aks-resource-group
      kubectl create namespace app1 --dry-run=client -o yaml | kubectl apply -f -
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml
