 apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: myappado22.azurecr.io/python-sample:latest
        ports:
        - containerPort: 80
